'Hello world!'.startswith('Hello')
print('Hello world!'.startswith('Hello'))
'Hello world!'.endswith('world!') 
print('Hello world!'.endswith('world!') )
'abc123'.startswith('abcdef')
print('abc123'.startswith('abcdef'))
'abc123'.endswith('12')
print('abc123'.endswith('12'))
'Hello world!'.startswith('Hello world!') 
print('Hello world!'.startswith('Hello world!') )
'Hello world!'.endswith('Hello world!')
print('Hello world!'.endswith('Hello world!'))
'Hello'.rjust(10)
print('Hello'.rjust(10))
'Hello'.rjust(20)
print('Hello'.rjust(20))
'Hello World'.rjust(20)
print('Hello World'.rjust(20))
'Hello'.ljust(10)
print('Hello'.ljust(10))
'Hello'.rjust(20, '*')
print('Hello'.rjust(20, '*'))
'Hello'.ljust(20, '-')
print('Hello'.ljust(20, '-'))
'Hello'.center(20)
print('Hello'.center(20))
'Hello'.center(20, '=') 
print('Hello'.center(20, '=') )
